### ISSUE TITLE
Database địa chỉ việtnam

### ISSUE THREAD

**Issue by nbao** [jetaimefrc/Database-provinces-districts-ward-VN-postgres#34]
Chào bác.
Cho mình hỏi bác có database toàn bộ địa chỉ ở việtnam kg? mình muốn viết một cái autocomplete nhập địa chỉ nó trả danh sách địa chỉ và tọa độ.
Cảm ơn bác.

**Comment by hoanghadu** [comment]
Toàn bộ địa chỉ thì may ra công ty giao hàng như GHTK hoặc Google biết, nhưng địa chỉ VN ko có chuẩn, nên dữ liệu chắc còn sai lệch nhiều và 2 công ty kia ko cung cấp.

Hiện tại có thể làm autocomplate đến mức phường xã thôi, bạn tham khảo dữ liệu tại: https://github.com/madnh/hanhchinhvn

**Comment by nhattran998** [comment]
@nbao Bạn lấy thông tin từ link github của bạn @hoanghadu cung cấp nhé 😆. Còn nếu không thì bạn thể dùng trực tiếp từ google api nhé https://developers.google.com/maps/documentation/places/web-service/search-find-place.
